/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package spectrex;

import static spectrex.ChoosePatient.idp;
import static spectrex.Seans.ids;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author Kirill
 */
public class KVVVreg extends javax.swing.JFrame {

    /**
     * Creates new form KVVVreg
     */
    public Connection cn = MedLogin.cn;
    public int idhs = MedLogin.idhs;
    public static int idkvvv;
    public JTextField textfields[];
    
    public KVVVreg() {
        initComponents();
        //ButtonSave.setEnabled(false);
        java.awt.Dimension dim = getToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getWidth()/2,
                dim.height/2 - this.getHeight()/2);
                this.textfields = new JTextField []{FieldD0, FieldD1, FieldD2, FieldD3, FieldD4, FieldD5, FieldD6, FieldD7,
                FieldD8, FieldD9, FieldD10, FieldD11, FieldD12, FieldD13, FieldD14, FieldD15,
                FieldD16, FieldD17, FieldD18, FieldD19, FieldD20, FieldD21, FieldD22, FieldD23,
                FieldD24, FieldD25, FieldD26, FieldD27, FieldD28, FieldD29, FieldD30, FieldD31
                };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        ButtonRefresh = new javax.swing.JButton();
        ButtonSave = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        ButtonStartClassifier = new javax.swing.JButton();
        ButtonZero = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        FieldD17 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        FieldD9 = new javax.swing.JTextField();
        FieldD24 = new javax.swing.JTextField();
        FieldD16 = new javax.swing.JTextField();
        FieldD10 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FieldD4 = new javax.swing.JTextField();
        FieldD19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FieldD25 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        FieldD11 = new javax.swing.JTextField();
        FieldD6 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FieldD7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FieldD14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        FieldD12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FieldD13 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        FieldD1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        FieldD5 = new javax.swing.JTextField();
        FieldD28 = new javax.swing.JTextField();
        FieldD2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        FieldD20 = new javax.swing.JTextField();
        FieldD26 = new javax.swing.JTextField();
        FieldD21 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        FieldD22 = new javax.swing.JTextField();
        FieldD8 = new javax.swing.JTextField();
        FieldD29 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FieldD23 = new javax.swing.JTextField();
        FieldD31 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        FieldD27 = new javax.swing.JTextField();
        FieldD18 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        FieldD0 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        FieldD15 = new javax.swing.JTextField();
        FieldD30 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        FieldD3 = new javax.swing.JTextField();
        ButtonOpenFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("spectrex/Bundle"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("KVVVreg.jPanel1.border.title"))); // NOI18N

        ButtonRefresh.setText(bundle.getString("KVVVreg.ButtonRefresh.text")); // NOI18N
        ButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshActionPerformed(evt);
            }
        });

        ButtonSave.setText(bundle.getString("KVVVreg.ButtonSave.text")); // NOI18N
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        ButtonCancel.setText(bundle.getString("KVVVreg.ButtonCancel.text")); // NOI18N
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        ButtonStartClassifier.setText(bundle.getString("KVVVreg.ButtonStartClassifier.text")); // NOI18N
        ButtonStartClassifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartClassifierActionPerformed(evt);
            }
        });

        ButtonZero.setText(bundle.getString("KVVVreg.ButtonZero.text")); // NOI18N
        ButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonZeroActionPerformed(evt);
            }
        });

        jLabel11.setText(bundle.getString("KVVVreg.jLabel11.text")); // NOI18N

        FieldD17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldD17ActionPerformed(evt);
            }
        });

        jLabel14.setText(bundle.getString("KVVVreg.jLabel14.text")); // NOI18N

        jLabel5.setText(bundle.getString("KVVVreg.jLabel5.text")); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel17.setText(bundle.getString("KVVVreg.jLabel17.text")); // NOI18N

        jLabel27.setText(bundle.getString("KVVVreg.jLabel27.text")); // NOI18N

        jLabel4.setText(bundle.getString("KVVVreg.jLabel4.text")); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setText(bundle.getString("KVVVreg.jLabel8.text")); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setText(bundle.getString("KVVVreg.jLabel1.text")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel23.setText(bundle.getString("KVVVreg.jLabel23.text")); // NOI18N

        jLabel25.setText(bundle.getString("KVVVreg.jLabel25.text")); // NOI18N

        jLabel18.setText(bundle.getString("KVVVreg.jLabel18.text")); // NOI18N

        jLabel7.setText(bundle.getString("KVVVreg.jLabel7.text")); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setText(bundle.getString("KVVVreg.jLabel15.text")); // NOI18N

        jLabel6.setText(bundle.getString("KVVVreg.jLabel6.text")); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel30.setText(bundle.getString("KVVVreg.jLabel30.text")); // NOI18N

        jLabel3.setText(bundle.getString("KVVVreg.jLabel3.text")); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel29.setText(bundle.getString("KVVVreg.jLabel29.text")); // NOI18N

        jLabel2.setText(bundle.getString("KVVVreg.jLabel2.text")); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setText(bundle.getString("KVVVreg.jLabel9.text")); // NOI18N

        jLabel21.setText(bundle.getString("KVVVreg.jLabel21.text")); // NOI18N

        jLabel26.setText(bundle.getString("KVVVreg.jLabel26.text")); // NOI18N

        FieldD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldD5ActionPerformed(evt);
            }
        });

        jLabel13.setText(bundle.getString("KVVVreg.jLabel13.text")); // NOI18N

        jLabel22.setText(bundle.getString("KVVVreg.jLabel22.text")); // NOI18N

        jLabel10.setText(bundle.getString("KVVVreg.jLabel10.text")); // NOI18N

        jLabel32.setText(bundle.getString("KVVVreg.jLabel32.text")); // NOI18N

        jLabel20.setText(bundle.getString("KVVVreg.jLabel20.text")); // NOI18N

        jLabel31.setText(bundle.getString("KVVVreg.jLabel31.text")); // NOI18N

        jLabel19.setText(bundle.getString("KVVVreg.jLabel19.text")); // NOI18N

        jLabel28.setText(bundle.getString("KVVVreg.jLabel28.text")); // NOI18N

        FieldD0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldD0ActionPerformed(evt);
            }
        });

        jLabel12.setText(bundle.getString("KVVVreg.jLabel12.text")); // NOI18N

        FieldD15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldD15ActionPerformed(evt);
            }
        });

        jLabel16.setText(bundle.getString("KVVVreg.jLabel16.text")); // NOI18N

        jLabel24.setText(bundle.getString("KVVVreg.jLabel24.text")); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldD1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(FieldD3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(FieldD4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(FieldD5, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(FieldD6, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(FieldD7, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(FieldD0)
                    .addComponent(FieldD2))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldD9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldD17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FieldD24, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD29, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD30, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD27, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD26, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldD28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FieldD1, FieldD3, FieldD4, FieldD5, FieldD6, FieldD7});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldD0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FieldD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD10)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FieldD3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FieldD4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FieldD28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldD5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(FieldD13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldD29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(FieldD6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldD22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldD14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldD30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldD8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldD16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldD24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldD9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldD17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldD25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(FieldD26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(FieldD7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldD23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldD15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldD31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FieldD0, FieldD1, FieldD2, FieldD3, FieldD4, FieldD5, FieldD6, FieldD7, jLabel6, jLabel7});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FieldD10, FieldD11, FieldD12, FieldD13, FieldD14, FieldD15, FieldD8, FieldD9});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FieldD16, FieldD17, FieldD18, FieldD19, FieldD20, FieldD21, FieldD22, FieldD23});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FieldD24, FieldD25, FieldD26, FieldD27, FieldD28, FieldD29, FieldD30, FieldD31});

        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD0, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FieldD3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ButtonOpenFile.setText(bundle.getString("KVVVreg.ButtonOpenFile.text")); // NOI18N
        ButtonOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonStartClassifier, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonStartClassifier)
                    .addComponent(ButtonRefresh)
                    .addComponent(ButtonZero)
                    .addComponent(ButtonOpenFile))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSave)
                    .addComponent(ButtonCancel))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        try {           
            float D[] = new float[32];
            String Sqlkvvv = "";
            for(int i = 0; i < 32; i++)
             D[i] = Float.parseFloat(textfields[i].getText().replace(',', '.'));   
           /* D[1] = Float.parseFloat(FieldD1.getText());
            D[2] = Float.parseFloat(FieldD2.getText());
            D[3] = Float.parseFloat(FieldD3.getText());
            D[4] = Float.parseFloat(FieldD4.getText());
            D[5] = Float.parseFloat(FieldD5.getText());
            D[6] = Float.parseFloat(FieldD6.getText());
            D[7] = Float.parseFloat(FieldD7.getText());
            
            D[8] = Float.parseFloat(FieldD8.getText());
            D[9] = Float.parseFloat(FieldD9.getText());
            D[10] = Float.parseFloat(FieldD10.getText());
            D[11] = Float.parseFloat(FieldD11.getText());
            D[12] = Float.parseFloat(FieldD12.getText());
            D[13] = Float.parseFloat(FieldD13.getText());
            D[14] = Float.parseFloat(FieldD14.getText());
            D[15] = Float.parseFloat(FieldD15.getText());
            
            D[16] = Float.parseFloat(FieldD16.getText());
            D[17] = Float.parseFloat(FieldD17.getText());
            D[18] = Float.parseFloat(FieldD18.getText());
            D[19] = Float.parseFloat(FieldD19.getText());
            D[20] = Float.parseFloat(FieldD20.getText());
            D[21] = Float.parseFloat(FieldD21.getText());
            D[22] = Float.parseFloat(FieldD22.getText());
            D[23] = Float.parseFloat(FieldD23.getText());
            
            D[24] = Float.parseFloat(FieldD24.getText());
            D[25] = Float.parseFloat(FieldD25.getText());
            D[26] = Float.parseFloat(FieldD26.getText());
            D[27] = Float.parseFloat(FieldD27.getText());
            D[28] = Float.parseFloat(FieldD28.getText());
            D[29] = Float.parseFloat(FieldD29.getText());
            D[30] = Float.parseFloat(FieldD30.getText());
            D[31] = Float.parseFloat(FieldD31.getText());
            */
            /*
            inst + diagnostic group in lists
            part 4
            */
            
            Sqlkvvv = "insert into kvvvfloat (D2, D3, D4, D5, D6, D8, D11, D15, " +
                    "D20, D26, D36, D40, D65, D85, D120, D150, " +
                    "D210, D290, D300, D520, D700, D950, D1300, D1700, " +
                    "D2300, D3100, D4200, D5600, D7600, D10200, D13800, D18500) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,"
                    + " ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try {
                PreparedStatement ps = cn.prepareStatement(Sqlkvvv);
                
                for(int i=0; i<32; i++)
                    ps.setFloat(i+1, D[i]);
                
                int n = ps.executeUpdate();
                
                if(n > 0)
                {
                    JOptionPane.showMessageDialog(null, "Successful saved");
                }
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
          //  this.dispose();
       
        
        /////////////////////
        
            Statement sta = cn.createStatement();
            ResultSet rs;

            rs = sta.executeQuery("select IdKV from kvvvfloat where " + 
                    "D2 = " + D[0] + 
                    " and D3 = " + D[1] +
                    " and D4 = " + D[2] +
                    " and D5 = " + D[3] +
                    " and D6 = " + D[4] +
                    " and D8 = " + D[5] +
                    " and D11 = " + D[6] +
                    " and D15 = " + D[7] +
                    " and D20 = " + D[8] +
                    " and D26 = " + D[9] +
                    " and D36 = " + D[10] +
                    " and D40 = " + D[11] +
                    " and D65 = " + D[12] +
                    " and D85 = " + D[13] +
                    " and D120 = " + D[14] +
                    " and D150 = " + D[15] +
                    " and D210 = " + D[16] +
                    " and D290 = " + D[17] +
                    " and D300 = " + D[18] +
                    " and D520 = " + D[19] +
                    " and D700 = " + D[20] +
                    " and D950 = " + D[21] +
                    " and D1300 = " + D[22] +
                    " and D1700 = " + D[23] +
                    " and D2300 = " + D[24] +
                    " and D3100 = " + D[25] +
                    " and D4200 = " + D[26] +
                    " and D5600 = " + D[27] +
                    " and D7600 = " + D[28] +
                    " and D10200 = " + D[29] +
                    " and D13800 = " + D[30] +
                    " and D18500 = " + D[31] + ";");
            if(!rs.first())
                JOptionPane.showMessageDialog(null, "Неверные КВВВ-данные");
            else {
                    idkvvv = rs.getInt("IdKV"); 
                   // JOptionPane.showMessageDialog(null, "idkvvv = " + idkvvv);
                    this.dispose();
                } 
                  
            try {                                               
            Statement s = cn.createStatement();
            java.util.Date now = new java.util.Date();
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat format2 = new SimpleDateFormat("HH:mm:ss");
            String d1 = format1.format(now);
            String t1 = format2.format(now);
            System.out.println(d1 + " " + t1);
         
            String Sql = "";
  
            Sql = "insert into journal (DateOfWork, TimeOfWork, IdHS, Enter, Quit, InputDataInTable, UseQuery) values (?, ?, ?, ?, ?, ?, ?)";
          
            try {
                PreparedStatement ps = cn.prepareStatement(Sql);
                ps.setString(1, d1);
                ps.setString(2, t1);
                ps.setInt(3, idhs);
                ps.setString(4, "0");
                ps.setString(5, "0");
                ps.setString(6, "KVVVfloat");
                ps.setString(7, "insert into KVVVfloat values(...)");
                
                int n = ps.executeUpdate();
                
                if(n <= 0)
                {
                    JOptionPane.showMessageDialog(null, "message_journal_BAD_Quit");
                }
            }
                         catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
                    
            }      
                           catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
                           }
             } catch (SQLException ex) {
            Logger.getLogger(KVVVreg.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshActionPerformed
        for(int i = 0; i < 32; i++)
            textfields[i].setText("");
      /*  FieldD29.setText("");
        FieldD6.setText("");
        FieldD14.setText("");
        FieldD22.setText("");
        FieldD30.setText("");
        FieldD7.setText("");
        FieldD15.setText("");
        FieldD23.setText("");
        FieldD31.setText("");
        FieldD0.setText("");
        FieldD8.setText("");
        FieldD16.setText("");
        FieldD24.setText("");
        FieldD9.setText("");
        FieldD17.setText("");
        FieldD1.setText("");
        FieldD18.setText("");
        FieldD25.setText("");
        FieldD10.setText("");
        FieldD2.setText("");
        FieldD11.setText("");
        FieldD26.setText("");
        FieldD3.setText("");
        FieldD19.setText("");
        FieldD27.setText("");
        FieldD4.setText("");
        FieldD12.setText("");
        FieldD20.setText("");
        FieldD28.setText("");
        FieldD5.setText("");
        FieldD13.setText("");
        FieldD21.setText("");*/
    }//GEN-LAST:event_ButtonRefreshActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonStartClassifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartClassifierActionPerformed
               
            float D[] = new float[32];
            try {
                for(int i = 0; i < 32; i++)
                    D[i] = Float.parseFloat(textfields[i].getText().replace(',', '.'));                                
            }
            
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        
       // BarGraph bg = new BarGraph(D, 800, 520, 25, 5);
            ChartData data = new ChartData();
            data.addData("Данные пациента", D);
        Charts.createBarChart(data, "", "Размеры частиц КВВВ, нм", "Среднее значение процентного вклада, %", new Dimension(800, 600));
        // <-- temp. for testing -->
       
        
        //float D[] = new float[32];
            try {
                float sum = 0;
                Boolean flag = false;
                for(int i = 0; i < 32; i++)
                {
                     D[i] = Float.parseFloat(textfields[i].getText().replace(',', '.'));   
                    if(D[i] < 0)
                        flag = true;
                    sum += D[i];
                }
                if((sum > 102 || sum < 98))
                {
                     JOptionPane.showMessageDialog(null, "Сумма значений некорректна");
                }
                else if(flag)
                {
                    JOptionPane.showMessageDialog(null, "Отрицательные значения недопустимы");
                }
                else
                {
           // NNClassifier nn = new NNClassifier("trmse0.net");
            NNClassifier nn = new NNClassifier("ova93735\\");
            int k = nn.classify(D);
          //  JOptionPane.showMessageDialog(null, k);
            new ResultClassifier(k).setVisible(true);
            }
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
		
    }//GEN-LAST:event_ButtonStartClassifierActionPerformed

    private void ButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonZeroActionPerformed
        for(int i = 0; i < 32; i++)
            textfields[i].setText("0");
        /*FieldD29.setText("0");
        FieldD6.setText("0");
        FieldD14.setText("0");
        FieldD22.setText("0");
        FieldD30.setText("0");
        FieldD7.setText("0");
        FieldD15.setText("0");
        FieldD23.setText("0");
        FieldD31.setText("0");
        FieldD0.setText("0");
        FieldD8.setText("0");
        FieldD16.setText("0");
        FieldD24.setText("0");
        FieldD9.setText("0");
        FieldD17.setText("0");
        FieldD1.setText("0");
        FieldD18.setText("0");
        FieldD25.setText("0");
        FieldD10.setText("0");
        FieldD2.setText("0");
        FieldD11.setText("0");
        FieldD26.setText("0");
        FieldD3.setText("0");
        FieldD19.setText("0");
        FieldD27.setText("0");
        FieldD4.setText("0");
        FieldD12.setText("0");
        FieldD20.setText("0");
        FieldD28.setText("0");
        FieldD5.setText("0");
        FieldD13.setText("0");
        FieldD21.setText("0");*/
    }//GEN-LAST:event_ButtonZeroActionPerformed

    private void FieldD15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldD15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldD15ActionPerformed

    private void FieldD0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldD0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldD0ActionPerformed

    private void FieldD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldD5ActionPerformed

    private void FieldD17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldD17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldD17ActionPerformed

    private void ButtonOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpenFileActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                Workbook wb = Workbook.getWorkbook(file);
                Sheet s = wb.getSheet(0);
                int row = s.getRows();
                int col = s.getColumns();
                float D[] = new float[32];
                for(int i = 1; i < row; i++)
                    for(int j = 0; j < col; j++)
                    {
                        Cell c = s.getCell(j, i);
                        D[j] = Float.parseFloat(c.getContents().replace(',', '.'));
                    }
                for(int i = 0; i < 32; i++)
                    textfields[i].setText(String.valueOf(D[i]));
            } catch (IOException ex) {
                Logger.getLogger(KVVVreg.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(KVVVreg.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_ButtonOpenFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KVVVreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KVVVreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KVVVreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KVVVreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KVVVreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonOpenFile;
    private javax.swing.JButton ButtonRefresh;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JButton ButtonStartClassifier;
    private javax.swing.JButton ButtonZero;
    private javax.swing.JTextField FieldD0;
    private javax.swing.JTextField FieldD1;
    private javax.swing.JTextField FieldD10;
    private javax.swing.JTextField FieldD11;
    private javax.swing.JTextField FieldD12;
    private javax.swing.JTextField FieldD13;
    private javax.swing.JTextField FieldD14;
    private javax.swing.JTextField FieldD15;
    private javax.swing.JTextField FieldD16;
    private javax.swing.JTextField FieldD17;
    private javax.swing.JTextField FieldD18;
    private javax.swing.JTextField FieldD19;
    private javax.swing.JTextField FieldD2;
    private javax.swing.JTextField FieldD20;
    private javax.swing.JTextField FieldD21;
    private javax.swing.JTextField FieldD22;
    private javax.swing.JTextField FieldD23;
    private javax.swing.JTextField FieldD24;
    private javax.swing.JTextField FieldD25;
    private javax.swing.JTextField FieldD26;
    private javax.swing.JTextField FieldD27;
    private javax.swing.JTextField FieldD28;
    private javax.swing.JTextField FieldD29;
    private javax.swing.JTextField FieldD3;
    private javax.swing.JTextField FieldD30;
    private javax.swing.JTextField FieldD31;
    private javax.swing.JTextField FieldD4;
    private javax.swing.JTextField FieldD5;
    private javax.swing.JTextField FieldD6;
    private javax.swing.JTextField FieldD7;
    private javax.swing.JTextField FieldD8;
    private javax.swing.JTextField FieldD9;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
